config/routes.rb
Rails.application.routes.draw do
  # get 'password_resets/new'
  # get 'password_resets/edit'
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to:"sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    #memberメソッド→ユーザーidを含むURLを扱うようになる(resourceに対してidを含むrouteを形成する)
    #collectメソッド→ユーザーに対して新しいメソッドを追加する(resourceに対して新しrouteを追加)
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :microposts, only: [:create, :destroy]
end

#名前付きルーティングは_path, _urlどちらでも訪問できるが_urlは絶対パス(https://)、_pathは相対パスの形で表現される

app/views/shared/_error_messages.html.erb
<%# errorパーシャルの引数としてオブジェクトが渡る %>
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts" >
    <%# @feed_itemsの各要素がMicropostクラスを持っていたため、RailsはMicropostのパーシャルを呼び出すことができる %>
    <%# railsが遠くから合致するパーシャルを探し出してくれる %>
    <%# app/views/microposts/_micropost.html.erb %>
    <%= render @feed_items %>
  </ol>
  <%# paginateメソッドがmicropostsコントローラーの中で呼ばれているため再度呼び出しがmicropostsコントローラーのindexメソッド %>
  <%# に設定されているため、それを変更する %>
  <%= will_paginate @feed_items, params: { controller: :static_pages, action: :home } %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost) do |f| %>
  <%# f.object→formのブロック変数に対して使用する事でブロック内でモデルオブジェクトを呼び出す事が出来る。 %>
  <%# f.objectは、form_withが持っている変数を使っているということ %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="image" >
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<%# pluralize→ふたつ目の単語を一つ目の数に合わせた形に変える（複数形） %>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>